const Map<String, String> ar = {
  'Login Screen': 'تسجيل الدخول إلى حسابك',
  "Username": "اسم المستخدم",
  'Write Username': "أدخل اسم المستخدم",
  'Password': "كلمة المرور",
  'Write Password': "أدخل كلمة المرور",
  'Login': "تسجيل الدخول",
  'Please fill in the blank fields.': "يرجى ملء الحقول الفارغة.",
  'Failed to login. Invalid response.': "فشل تسجيل الدخول. استجابة غير صالحة.",
  'Oops! It seems there was an issue with your request. Please try again.':
      "عذرًا! يبدو أن هناك مشكلة في طلبك. يرجى المحاولة مرة أخرى.",
  'Access Denied! You don\'t have permission to view this content.':
      "تم رفض الوصول! ليس لديك إذن لعرض هذا المحتوى.",
  'Sorry, we couldn\'t find what you were looking for. Please try again later.':
      "عذرًا، لم نتمكن من العثور على ما تبحث عنه. يرجى المحاولة لاحقًا.",
  'Something went wrong. Please try again or contact support if the issue persists.':
      "حدث خطأ ما. يرجى المحاولة مرة أخرى أو الاتصال بالدعم إذا استمرت المشكلة.",
  'username is invalid': "اسم المستخدم غير صالح",
  'the password is wrong': "كلمة المرور غير صحيحة",
  'Please check your internet connection.': "يرجى التحقق من اتصالك بالإنترنت.",
  'No internet connection': "لا يوجد اتصال بالإنترنت.",
  'Password updated successfully': 'تم تحديث كلمة المرور بنجاح',
  'User updated successfully': 'تم تحديث المستخدم بنجاح',
  'Error fetching mission data': 'خطأ في جلب بيانات البعثة',
  "Failed to load Mission Status": "فشل في تحميل حالة البعثة",
  'Cancel': "إلغاء",
  'Connection problem': "مشكلة اتصال",
  'Verifying...': "جارٍ التحقق...",
  "Delegate": "تفويض",
  "Every thing \nunder controlle": "كل شيء \nتحت السيطرة",
  'Feedback updated successfully': 'تم تحديث الملاحظة بنجاح',
  'Failed to update feedback': 'فشل في تحديث الملاحظة',
  'No Internet Connection': 'لا يوجد اتصال بالإنترنت',
  'Something went wrong': 'حدث خطأ ما',
  'Feedback added successfully': 'تمت إضافة الملاحظة بنجاح',
  "Failed to load annexes": "فشل في تحميل الملاحق",
  "Get Started": "ابدأ",
  "You are not allowed to enter.": "غير مسموح لك بالدخول.",
  "OK": "حسنًا",
  "Please specify": " يرجى التحديد السبب",
  "Select Reasons": "اختر السبب",
  "Loading data...": "جارٍ تحميل البيانات...",
  "Your account is blocked, please contact our support team.":
      "تم حظر حسابك، يرجى الاتصال بفريق الدعم الخاص بنا.",
  "Select Date": "اختر التاريخ",
  "Profile": "الملف الشخصي",
  "Feedbacks": "الملاحظات",
  "Feedback cannot be edited": "لا يمكن تعديل الملاحظة.",
  "Yes": "نعم",
  "No feedback available.": "لا توجد ملاحظات متوفرة.",
  "A mission can only have one associated feedback entry.":
      "يمكن أن تحتوي البعثة على إدخال ملاحظات واحد فقط.",
  "Feedback": "الملاحظة",
  "Exit App": "الخروج من التطبيق",
  "My FeedBack": "ملاحظاتي",
  "All Clients": "جميع العملاء",
  "All Missions": "جميع البعثات",
  "Updated Date :": "تاريخ التحديث :",
  "My Mission": "بعثتي",
  "Are you sure you want to exit the app?":
      "هل أنت متأكد من أنك تريد الخروج من التطبيق؟",
  "No": "لا",
  "No Company found": "لم يتم العثور على شركة",
  "Select Company": "اختر الشركة",
  "No Annex found": "لم يتم العثور على ملحق",
  "Select Annex": "اختر الملحق",
  "Loading name...": "جارٍ تحميل الاسم...",
  "Add \n Mission": "إضافة \n بعثة",
  "Add \n Feedback": "إضافة \n ملاحظات",
  'error fetching data': 'خطأ في جلب البيانات',
  "Percentage": "النسبة المئوية",
  "With Mission": "مع البعثة",
  "With Out Mission": "بدون  بعثة",
  "All": "الكل",
  "Statistics Feedback": "إحصائيات الملاحظات",
  "Completed": "مكتمل",
  "In Progress": "قيد التنفيذ",
  "Canceled": "ملغي",
  "Statistics Missions": "إحصائيات البعثات",
  "Log Out": "تسجيل الخروج",
  'Do you really want to log out of the account?':
      'هل تريد حقًا تسجيل الخروج من الحساب؟',
  "Quick Actions": "الإجراءات السريعة",
  "Settings and Preferences": "الإعدادات والتفضيلات",
  'Selected language': 'اللغة المحددة',
  'Fetching data...': 'جارٍ جلب البيانات...',
  "Active": "نشط",
  "Inactive": "غير نشط",
  "In English is \"Verifying...\"": "بالإنجليزية \"جارٍ التحقق...\"",
  "Account": "الحساب",
  "Annex": "الملحق",
  "Company": "الشركة",
  "Version.": "الإصدار.",
  "Send Your Suggestion": "أرسل اقتراحك",
  "Write your opinion or suggestion here...": "اكتب رأيك أو اقتراحك هنا...",
  "Suggestions": "الاقتراحات",
  "User Information": "معلومات المستخدم",
  "Edit Information": "تعديل المعلومات",
  "First Name": "الاسم الأول",
  'Please enter a First Name': "يرجى إدخال الاسم الأول",
  "Last Name": "اسم العائلة",
  'Please enter a last Name': "يرجى إدخال اسم العائلة",
  "Edit Basic Information": "تعديل المعلومات الأساسية",
  "Change Password": "تغيير كلمة المرور",
  "Current Password": "كلمة المرور الحالية",
  "Enter Current Password": "أدخل كلمة المرور الحالية",
  'Please enter a Current Password': "يرجى إدخال كلمة المرور الحالية",
  "New Password": "كلمة المرور الجديدة",
  "Enter New Password": "أدخل كلمة المرور الجديدة",
  'Please enter a New Password': "يرجى إدخال كلمة المرور الجديدة",
  "Confirm Password": "تأكيد كلمة المرور",
  "Enter the New Password": "أدخل كلمة المرور الجديدة",
  'Please enter a Confirm Password': "يرجى إدخال تأكيد كلمة المرور",
  "Make sure the password matches.": "تأكد من تطابق كلمة المرور.",
  "Save": "حفظ",
  "Mission created successfully!": "تم إنشاء البعثة بنجاح!",
  "Contact Us": "اتصل بنا",
  "app dec": "وصف التطبيق",
  "About the application": "حول التطبيق",
  "View All Missions": "عرض جميع البعثات",
  "is required.": "مطلوب.",
  "No Missions found": "لم يتم العثور على بعثات",
  "Status": "الحالة",
  "Creator": "المنشئ",
  "Label": "العنوان",
  "Last Missions": "آخر البعثات",
  "Select another annex": "اختر ملحقًا آخر",
  "No company found, please select another annex.":
      "لم يتم العثور على شركة، يرجى اختيار ملحق آخر.",
  "View All Feedback": "عرض جميع الملاحظات",
  "Last Feedbacks": "آخر الملاحظات",
  'New': "جديد",
  'Unknown Status': "حالة غير معروفة",
  'Confirmation': "تأكيد",
  'Are you sure to Start the Mission?': "هل أنت متأكد من بدء البعثة؟",
  'Are you sure to Stop the Mission?': "هل أنت متأكد من إيقاف البعثة؟",
  'No description available': "لا يوجد وصف متاح",
  'Created At': "تاريخ الإنشاء",
  'Editor Username': "اسم مستخدم المحرر",
  'No editor assigned': "لم يتم تعيين محرر",
  'Creator Username': "اسم مستخدم المنشئ",
  "Add Feedback": "إضافة ملاحظة",
  'Feedback Details': "تفاصيل الملاحظة",
  'Are you sure to complete the Mission?': "هل أنت متأكد من إكمال البعثة؟",
  'Other Details': "تفاصيل أخرى",
  'Region:': "المنطقة:",
  'Create Feedback': "إنشاء ملاحظة",
  'Sold:': "المبيعات:",
  'Turnover:': "الإيرادات:",
  'Cashing In:': "التدفقات النقدية:",
  'This field': "هذا الحقل",
  'must be at least': "يجب أن يكون على الأقل",
  'characters.': "حروف.",
  "is required": "مطلوب",
  "must be no more than": "يجب ألا يتجاوز",
  "Mission Details": "تفاصيل البعثة",
  "characters": "حروف",
  "Missions": "البعثات",
  "Email is required": "البريد الإلكتروني مطلوب",
  "Please enter a valid email address": "يرجى إدخال عنوان بريد إلكتروني صحيح",
  "Password must be at least": "يجب أن تكون كلمة المرور على الأقل",
  "Phone number is required": "رقم الهاتف مطلوب",
  "Please enter a valid phone number": "يرجى إدخال رقم هاتف صحيح",
  ' is required.': " مطلوب.",
  'Potential:': "القدرة:",
  'Please enter a valid phone number.': "يرجى إدخال رقم هاتف صالح.",
  "Client Since:": "عميل منذ:",
  'Contact Details': "تفاصيل الاتصال",
  "Report": "تقرير",
  "Created by:": "تم الإنشاء بواسطة:",
  "My Feedbacks": "ملاحظاتي",
  'Client Profile': "ملف العميل",
  'No Date Available': "لا توجد بيانات متاحة",
  'Feedback not found.': "لم يتم العثور على ملاحظة.",
  'No Name': "لا يوجد اسم",
  "Search clients...": "البحث عن العملاء...",
  'No clients available.': "لا توجد عملاء متاحين.",
  "Select the client": "اختر العميل",
  'No Email': "لا يوجد بريد إلكتروني",
  'No Title': "لا يوجد عنوان",
  "Username is required": "اسم المستخدم مطلوب",
  "Email": "البريد الإلكتروني",
  "Password must be at least 4 characters long":
      "يجب أن يتكون كلمة المرور من 4 أحرف على الأقل",
  "Username must be at least 4 characters long":
      "يجب أن يتكون اسم المستخدم من 4 أحرف على الأقل",
  "Add Mission": "إضافة بعثة",
  "Client": "عميل",
  "Select": "حدد",
  "This user is blocked": "هذا المستخدم محظور.",
  'Request Date:': "تاريخ الطلب:",
  "Re-enter New Password": "أعد إدخال كلمة المرور الجديدة",
  "The username field is invalid.": " اسم المستخدم غير صالح.",
  "Start Mission": "بدء البعثة",
  'Select End Date': "حدد تاريخ الانتهاء",
  "Password is required": "كلمة المرور مطلوبة",
  "The password field is incorrect": "  كلمة المرور غير صحيحة",
  "Actions": "إجراءات",
  'Phone': "الهاتف",
  'Address': "العنوان",
  "Photos": "صور",
  "Camera": "كاميرا",
  'Business Information': "معلومات العمل",
  'End Date': "تاريخ الانتهاء:",
  'Creator Information': "معلومات المنشئ",
  'Username:': "اسم المستخدم:",
  'Open Settings': "فتح الإعدادات",
  "Date:": " :تاريخ الانشاء ",
  'Edit Feedback': 'تعديل الملاحظة',
  'Gallery': 'المعرض',
  'Location services are required for this feature. Please enable them in settings.':
      'خدمات الموقع مطلوبة لهذه الميزة. يرجى تفعيلها في الإعدادات.',
  'Location Services Disabled': 'خدمات الموقع معطلة',
  'No Images available': 'لا توجد صور متاحة',
  'Select Start Date': 'اختر تاريخ البداية',
  'Start Date': 'تاريخ البداية:',
  'Select Date Range': 'حدد نطاق التواريخ',
  'No missions available': 'لا توجد بعثات متاحة',
  'Language Selection': 'اختيار اللغة',
  'Choose your preferred language to make it easier for you to use the application':
      'اختر لغتك المفضلة لتسهيل استخدام التطبيق.',
  "My Missions": "بعثاتي",
  'No companies available.': 'لا توجد شركات متاحة.',
  'Description': 'الوصف',
  "Edit Profile": "تعديل الملف الشخصي",
  'Selected Images': 'الصور المختارة',
  'Loading images:': 'جارٍ تحميل الصور:',
  "Failed to load reasons:": "فشل في تحميل الأسباب:",
  'Update Feedback': 'تحديث الملاحظة',
  'No reasons available': 'لا توجد أسباب متاحة',
  'Please enter a description': 'يرجى إدخال وصف',
  'Create Mission': 'إنشاء بعثة',
  'Companies': 'الشركات',
  'Updated:': 'تم التحديث:',
  "Description Required *": "الوصف مطلوب *",
  'Created:': 'تم الإنشاء:',
  "Request Date Required *": "تاريخ الطلب مطلوب *",
  "Change Language": "تغيير اللغة",
  "This feedback has a mission.": "هذه الملاحظة لها بعثة.",
  'Company name:': 'اسم الشركة:',
  "A new version of the app is available. Update now to enjoy the latest features and improvements.":
      "إصدار جديد من التطبيق متوفر. حدث الآن للاستمتاع بأحدث الميزات والتحسينات.",
  "Later": "لاحقًا",
  "Update Now": "حدث الآن",
  "All feedbacks": "جميع الملاحظات.",
  "Tel": "الهاتف",
  "Full Name": "الاسم الكامل",
  "All Feedbacks": "Tous les Feedbacks.",
  "About the Application": "عن التطبيق",
  'We introduce an exclusive application designed for customer delegates, enabling them to effortlessly record their notes. This app facilitates the organization of information and the effective tracking of customer interactions, ultimately enhancing service quality and improving the overall customer experience.':
      'نقدم تطبيقًا حصريًا مصممًا لمندوبي العملاء، مما يتيح لهم تسجيل ملاحظاتهم بسهولة. يُسهل هذا التطبيق تنظيم المعلومات وتتبع التفاعلات مع العملاء بفعالية، مما يعزز جودة الخدمة ويحسن تجربة العملاء بشكل عام.',
  'Start': 'ابدأ',
  'Owner Respond': 'رد المالك',
  'Responsible Respond': 'رد المسؤول',
  'Responsible close': 'إغلاق المسؤول',
  'Close': 'إغلاق',
  'Responsible:': 'المسؤول:',
  'View All Task': 'عرض جميع المهام',
  'No Task found': 'لم يتم العثور على مهام',
  'Since': 'منذ',
  'Responsible': 'المسؤول',
  'Last Tasks': 'آخر المهام',
  'Revert cancellation': 'إلغاء الإلغاء',
  'My Assigned': 'المخصص لي',
  'My Created': 'إنشائي',
  'My Supervised': 'تحت إشرافي',
  'message': 'رسالة',
  'Type a message...': 'اكتب رسالة...',
  'File': 'ملف',
  'Task not found': 'المهمة غير موجودة',
  'Task Details': 'تفاصيل المهمة',
  'Create At': 'تم الإنشاء في',
  'Deadline': 'الموعد النهائي',
  'Started': 'تم البدء',
  'Not started': 'لم يبدأ',
  'Observer': 'مراقب',
  'Owner': 'المالك',
  'PDF Gallery': 'معرض PDF',
  'All files': 'جميع الملفات',
  'Image Gallery': 'معرض الصور',
  'Histories': 'التواريخ',
  'Discussion': 'مناقشة',
  'Information': 'معلومات',
  'Invalid Date': 'تاريخ غير صالح',
  'Unknown': 'غير معروف',
  'All Task': 'جميع المهام',
  'No Task available': 'لا توجد مهام متاحة',
  'Update': 'تحديث',
  'Label must be at least 4 characters long':
      'يجب أن يتكون التسمية من 4 أحرف على الأقل',
  'Label is required': 'التسمية مطلوبة',
  'Select Observator': 'حدد المراقب',
  'Select Responsable': 'حدد المسؤول',
  'Edite Task': 'تحرير المهمة',
  'add Task': 'إضافة مهمة',
  'Description must be at least 4 characters long':
      'يجب أن تكون الوصف مكونًا من 4 أحرف على الأقل',
  'Description is required': 'الوصف مطلوب',
  'Create Task': 'إنشاء مهمة',
  'Pick a date': 'اختر تاريخًا',
  'Selected Date': 'التاريخ المحدد',
  'Files': 'الملفات',
  'Expired': 'منتهى الصلاحية',
  'Remaining:': 'متبقي:',
  'year': 'سنة',
  'day': 'يوم',
  'hour': 'ساعة',
  'minute': 'دقيقة',
  'second': 'ثانية',
  'Add \n Task': 'إضافة \n مهمة',
  'Statistics Tasks': 'إحصائيات المهام',
  'Responsible Closed': 'أغلق المسؤول',
  'Task': 'المهمة',
  'Closed': 'مغلق',
  'ago': 'منذ',
  'Failed to update task status': 'فشل في تحديث حالة المهمة',
  'Error fetching Task data': 'خطأ في جلب بيانات المهمة',
  'Task created successfully': 'تم إنشاء المهمة بنجاح',
  'Failed to create task': 'فشل في إنشاء المهمة',
  'Error updating task': 'خطأ في تحديث المهمة',
  'Task updated successfully': 'تم تحديث المهمة بنجاح',
  'Date': 'تاريخ',
};
