const Map<String, String> fr = {
  'Login Screen': 'Connectez-vous à votre compte',
  "Username": "Nom d'utilisateur",
  'Write Username': "Entrez le nom d'utilisateur",
  'Password': "Mot de passe",
  'Write Password': "Entrez le mot de passe",
  'Login': "Connexion",
  'Please fill in the blank fields.': "Veuillez remplir les champs vides.",
  'Failed to login. Invalid response.':
      "Échec de la connexion. Réponse invalide.",
  'Oops! It seems there was an issue with your request. Please try again.':
      "Oups! Il semble qu'il y ait un problème avec votre demande. Veuillez réessayer.",
  'Access Denied! You don\'t have permission to view this content.':
      "Accès refusé! Vous n'avez pas la permission de voir ce contenu.",
  'Sorry, we couldn\'t find what you were looking for. Please try again later.':
      "Désolé, nous n'avons pas pu trouver ce que vous cherchiez. Veuillez réessayer plus tard.",
  'Something went wrong. Please try again or contact support if the issue persists.':
      "Un problème est survenu. Veuillez réessayer ou contacter le support si le problème persiste.",
  'username is invalid': "Le nom d'utilisateur est invalide",
  'the password is wrong': "Le mot de passe est incorrect",
  'Please check your internet connection.':
      "Veuillez vérifier votre connexion Internet.",
  'No internet connection': "Pas de connexion Internet.",
  'Password updated successfully': 'Mot de passe mis à jour avec succès',
  'User updated successfully': 'Utilisateur mis à jour avec succès',
  'Error fetching mission data':
      'Erreur lors de la récupération des données de la mission',
  "Failed to load Mission Status":
      "Échec du chargement de l'état de la mission",
  'Cancel': "Annuler",
  'Connection problem': "Problème de connexion",
  'Verifying...': "Vérification...",
  "Delegate": "Déléguer",
  "Every thing \nunder controlle": "Tout est \nsous contrôle",
  'Feedback updated successfully': 'Retour mis à jour avec succès',
  'Failed to update feedback': 'Échec de la mise à jour du retour',
  'No Internet Connection': 'Pas de connexion Internet',
  'Something went wrong': 'Quelque chose s\'est mal passé',
  'Feedback added successfully': 'Retour ajouté avec succès',
  "Failed to load annexes": "Échec du chargement des annexes",
  "Get Started": "Commencer",
  "You are not allowed to enter.": "Vous n'êtes pas autorisé à entrer.",
  "OK": "D'accord",
  "Please specify": "Veuillez préciser",
  "Select Reasons": "Sélectionnez les raisons",
  "Loading data...": "Chargement des données...",
  "Your account is blocked, please contact our support team.":
      "Votre compte est bloqué, veuillez contacter notre équipe de support.",
  "Select Date": "Sélectionner la date",
  "Profile": "Profil",
  "Feedbacks": "Retours",
  "Feedback": "Retour",
  "My FeedBack": "Mon Retour",
  "All Clients": "Tous les clients",
  "All Missions": "Toutes les missions",
  "Updated Date :": "Date de mise à jour :",
  "My Mission": "Ma mission",
  "No Company found": "Aucune entreprise trouvée",
  "Select Company": "Sélectionner l'entreprise",
  "No Annex found": "Aucun annexe trouvé",
  "Select Annex": "Sélectionner l'annexe",
  "Loading name...": "Chargement du nom...",
  "Add \n Mission": "Ajouter \n Mission",
  "Add \n Feedback": "Ajouter \n Retour",
  "Percentage": "Pourcentage",
  "With Mission": "Avec mission",
  "With Out Mission": "Sans mission",
  "All": "Tous",
  "Statistics Feedback": "Statistiques des Retours",
  "Completed": "Terminé",
  "In Progress": "En cours",
  "Canceled": "Annulé",
  "Statistics Missions": "Statistiques des missions",
  "Log Out": "Déconnexion",
  'Do you really want to log out of the account?':
      'Voulez-vous vraiment vous déconnecter du compte ?',
  "Quick Actions": "Actions rapides",
  "Settings and Preferences": "Paramètres et préférences",
  'Selected language': 'Langue sélectionnée',
  'Fetching data...': 'Récupération des données...',
  "Active": "Actif",
  "Inactive": "Inactif",
  "In English is \"Verifying...\"": "En anglais, c'est \"Vérification...\"",
  "Account": "Compte",
  "Annex": "Annexe",
  "Company": "Entreprise",
  "Version.": "Version.",
  "Send Your Suggestion": "Envoyez votre suggestion",
  "Write your opinion or suggestion here...":
      "Écrivez votre opinion ou votre suggestion ici...",
  "Suggestions": "Suggestions",
  "User Information": "Informations utilisateur",
  "Edit Information": "Modifier les informations",
  "First Name": "Prénom",
  'Please enter a First Name': 'Veuillez entrer un prénom',
  "Last Name": "Nom de famille",
  'Please enter a last Name': 'Veuillez entrer un nom de famille',
  "Edit Basic Information": "Modifier les informations de base",
  "Change Password": "Changer le mot de passe",
  "Current Password": "Mot de passe actuel",
  "Enter Current Password": "Entrez le mot de passe actuel",
  'Please enter a Current Password': 'Veuillez entrer un mot de passe actuel',
  "New Password": "Nouveau mot de passe",
  "Enter New Password": "Entrez le nouveau mot de passe",
  'Please enter a New Password': 'Veuillez entrer un nouveau mot de passe',
  "Confirm Password": "Confirmer le mot de passe",
  "Enter the New Password": "Entrez le nouveau mot de passe",
  'Please enter a Confirm Password':
      'Veuillez entrer une confirmation de mot de passe',
  "Make sure the password matches.":
      "Assurez-vous que le mot de passe correspond.",
  "Save": "Enregistrer",
  "Contact Us": "Contactez-nous",
  "app dec": "découverte de l'application",
  "About the application": "À propos de l'application",
  "View All Missions": "Voir toutes les missions",
  "No Missions found": "Aucune mission trouvée",
  "Status": "Statut",
  "Creator": "Créateur",
  "Label": "Étiquette",
  "Last Missions": "Dernières missions",
  "Select another annex": "Sélectionnez une autre annexe",
  "No company found, please select another annex.":
      "Aucune entreprise trouvée, veuillez sélectionner une autre annexe.",
  "View All Feedback": "Voir tous les Retours",
  "Last Feedbacks": "Derniers Retours",
  'New': 'Nouveau',
  'Unknown Status': 'Statut inconnu',
  'Confirmation': 'Confirmation',
  'Are you sure to Start the Mission?':
      'Êtes-vous sûr de commencer la mission ?',
  'Are you sure to Stop the Mission?':
      'Êtes-vous sûr de vouloir arrêter la mission ?',
  'No description available': 'Aucune description disponible',
  'Created At': 'Créé le',
  'Editor Username': 'Nom d\'utilisateur de l\'éditeur',
  'No editor assigned': 'Aucun éditeur assigné',
  'Creator Username': 'Nom d\'utilisateur du créateur',
  "Add Feedback": "Ajouter un Retour",
  'Feedback Details': 'Détails du Retour',
  'Are you sure to complete the Mission?':
      'Êtes-vous sûr de vouloir compléter la mission ?',
  'Other Details': 'Autres détails',
  'Region:': 'Région :',
  'Create Feedback': 'Créer un Retour',
  'Sold:': 'Vendu :',
  'Cashing In:': 'Encaissement :',
  'Potential:': 'Potentiel :',
  "Client Since:": "Client depuis :",
  'Contact Details': 'Détails de contact',
  "Created by:": "Créé par :",
  "My Feedbacks": "Mes Retours",
  'Client Profile': 'Profil du client',
  'No Date Available': 'Aucune date disponible',
  'Feedback not found.': 'Retour non trouvé.',
  'No Name': 'Aucun nom',
  "Search clients...": "Rechercher des clients...",
  'No clients available.': 'Aucun client disponible.',
  "Select the client": "Sélectionnez le client",
  'No Email': 'Aucun email',
  'No Title': 'Aucun titre',
  "Add Mission": "Ajouter une mission",
  'Request Date:': 'Date de demande :',
  "Start Mission": "Démarrer la mission",
  'Select End Date': 'Sélectionner la date de fin',
  'Phone': 'Téléphone',
  'Address': 'Adresse',
  'Business Information': 'Informations sur l\'entreprise',
  'End Date:': 'Date de fin :',
  'Creator Information': 'Informations sur le créateur',
  'Username:': 'Nom d\'utilisateur :',
  'Open Settings': 'Ouvrir les paramètres',
  "Date:": "Date :",
  'Edit Feedback': 'Modifier le Retour',
  'Gallery': 'Galerie',
  'Location services are required for this feature. Please enable them in settings.':
      'Les services de localisation sont requis pour cette fonctionnalité. Veuillez les activer dans les paramètres.',
  'Location Services Disabled': 'Services de localisation désactivés',
  'No Images available': 'Aucune image disponible',
  'Select Start Date': 'Sélectionner la date de début',
  'Start Date:': 'Date de début :',
  'Select Date Range': 'Sélectionner la plage de dates',
  'No missions available': 'Aucune mission disponible',
  'Language Selection': 'Sélection de la langue',
  'Choose your preferred language to make it easier for you to use the application':
      'Choisissez votre langue préférée pour faciliter l\'utilisation de l\'application',
  "My Missions": "Mes missions",
  'No companies available.': 'Aucune entreprise disponible.',
  'Description': 'Description',
  "Edit Profile": "Modifier le profil",
  'Selected Images': 'Images sélectionnées',
  'Loading images:': 'Chargement des images :',
  "Failed to load reasons:": "Échec du chargement des raisons :",
  'Update Feedback': 'Mettre à jour le Retour',
  'No reasons available': 'Aucune raison disponible',
  'Please enter a description': 'Veuillez entrer une description',
  'Create Mission': 'Créer une mission',
  'Companies': 'Entreprises',
  'Updated:': 'Mis à jour :',
  "Description Required *": "Description requise *",
  'Created:': 'Créé :',
  "Request Date Required *": "Date de demande requise *",
  "Change Language": "Changer la langue",
  'Company name:': 'Nom de l’entreprise :',
  "About the Application": "À propos de l'application",
  'We introduce an exclusive application designed for customer delegates, enabling them to effortlessly record their notes. This app facilitates the organization of information and the effective tracking of customer interactions, ultimately enhancing service quality and improving the overall customer experience.':
      'Nous vous présentons une application exclusive conçue pour les délégués clients, leur permettant d\'enregistrer facilement leurs notes. Cette application facilite l\'organisation des informations et le suivi efficace des interactions avec les clients, améliorant ainsi la qualité du service et l\'expérience globale du client.'
};
