const Map<String, String> fr = {
  'Login Screen': 'Connectez-vous à votre compte',
  "Username": "Nom d'utilisateur",
  'Write Username': "Entrez le nom d'utilisateur",
  'Password': "Mot de passe",
  'Write Password': "Entrez le mot de passe",
  'Login': "Connexion",
  'Please fill in the blank fields.': "Veuillez remplir les champs vides.",
  'Failed to login. Invalid response.':
      "Échec de la connexion. Réponse invalide.",
  'Oops! It seems there was an issue with your request. Please try again.':
      "Oups! Il semble qu'il y ait un problème avec votre demande. Veuillez réessayer.",
  'Access Denied! You don\'t have permission to view this content.':
      "Accès refusé! Vous n'avez pas la permission de voir ce contenu.",
  'Sorry, we couldn\'t find what you were looking for. Please try again later.':
      "Désolé, nous n'avons pas pu trouver ce que vous cherchiez. Veuillez réessayer plus tard.",
  'Something went wrong. Please try again or contact support if the issue persists.':
      "Un problème est survenu. Veuillez réessayer ou contacter le support si le problème persiste.",
  'username is invalid': "Le nom d'utilisateur est invalide",
  'the password is wrong': "Le mot de passe est incorrect",
  'Please check your internet connection.':
      "Veuillez vérifier votre connexion Internet.",
  'No internet connection': "Pas de connexion Internet.",
  'Password updated successfully': 'Mot de passe mis à jour avec succès',
  'User updated successfully': 'Utilisateur mis à jour avec succès',
  'Error fetching mission data':
      'Erreur lors de la récupération des données de la mission',
  "Failed to load Mission Status":
      "Échec du chargement de l'état de la mission",
  'Cancel': "Annuler",
  'Connection problem': "Problème de connexion",
  'Verifying...': "Vérification...",
  "Delegate": "Déléguer",
  "Every thing \nunder controlle": "Tout est \nsous contrôle",
  'Feedback updated successfully': 'Feedback mis à jour avec succès',
  'Failed to update feedback': 'Échec de la mise à jour du Feedback',
  'No Internet Connection': 'Pas de connexion Internet',
  'Something went wrong': 'Quelque chose s\'est mal passé',
  'Feedback added successfully': 'Feedback ajouté avec succès',
  "Failed to load annexes": "Échec du chargement des annexes",
  "Get Started": "Commencer",
  "You are not allowed to enter.": "Vous n'êtes pas autorisé à entrer.",
  "OK": "D'accord",
  "Please specify": "Veuillez préciser",
  "Select Reasons": "Sélectionnez les raisons",
  "Loading data...": "Chargement des données...",
  "Your account is blocked, please contact our support team.":
      "Votre compte est bloqué, veuillez contacter notre équipe de support.",
  "Select Date": "Sélectionner la date",
  "Profile": "Profil",
  "Feedbacks": "Feedbacks",
  "Feedback cannot be edited": "Feedback ne peut pas être modifié.",
  "Yes": "Oui",
  "No feedback available.": "Aucun Feedback disponible.",
  "A mission can only have one associated feedback entry.":
      "Une mission ne peut avoir qu'une seule entrée de retour associée.",
  "Feedback": "Feedback",
  "Exit App": "Quitter l'application",
  "My FeedBack": "Mon Feedback",
  "All Clients": "Tous les clients",
  "All Missions": "Toutes les missions",
  "Updated Date :": "Date de mise à jour :",
  "My Mission": "Ma mission",
  "Are you sure you want to exit the app?":
      "Êtes-vous sûr de vouloir quitter l'application ?",
  "No": "Non",
  "No Company found": "Aucune entreprise trouvée",
  "Select Company": "Sélectionner l'entreprise",
  "No Annex found": "Aucun annexe trouvé",
  "Select Annex": "Sélectionner l'annexe",
  "Loading name...": "Chargement du nom...",
  "Add \n Mission": "Ajouter \n Mission",
  "Add \n Feedback": "Ajouter \n Feedback",
  "Percentage": "Pourcentage",
  "With Mission": "Avec mission",
  "With Out Mission": "Sans mission",
  "All": "Tous",
  "Statistics Feedback": "Statistiques des Feedbacks",
  "Completed": "Terminé",
  "In Progress": "En cours",
  "Canceled": "Annulé",
  "Statistics Missions": "Statistiques des missions",
  "Log Out": "Déconnexion",
  'Do you really want to log out of the account?':
      'Voulez-vous vraiment vous déconnecter du compte ?',
  "Quick Actions": "Actions rapides",
  "Settings and Preferences": "Paramètres et préférences",
  'Selected language': 'Langue sélectionnée',
  'Fetching data...': 'Récupération des données...',
  "Active": "Actif",
  "Inactive": "Inactif",
  "In English is \"Verifying...\"": "En anglais, c'est \"Vérification...\"",
  "Account": "Compte",
  "Annex": "Annexe",
  "Company": "Entreprise",
  "Version.": "Version.",
  "Send Your Suggestion": "Envoyez votre suggestion",
  "Write your opinion or suggestion here...":
      "Écrivez votre opinion ou votre suggestion ici...",
  "Suggestions": "Suggestions",
  "User Information": "Informations utilisateur",
  "Edit Information": "Modifier les informations",
  "First Name": "Prénom",
  'Please enter a First Name': 'Veuillez entrer un prénom',
  "Last Name": "Nom de famille",
  'Please enter a last Name': 'Veuillez entrer un nom de famille',
  "Edit Basic Information": "Modifier les informations de base",
  "Change Password": "Changer le mot de passe",
  "Current Password": "Mot de passe actuel",
  "Enter Current Password": "Entrez le mot de passe actuel",
  'Please enter a Current Password': 'Veuillez entrer un mot de passe actuel',
  "New Password": "Nouveau mot de passe",
  "Enter New Password": "Entrez le nouveau mot de passe",
  'Please enter a New Password': 'Veuillez entrer un nouveau mot de passe',
  "Confirm Password": "Confirmer le mot de passe",
  "Enter the New Password": "Entrez le nouveau mot de passe",
  'Please enter a Confirm Password':
      'Veuillez entrer une confirmation de mot de passe',
  "Make sure the password matches.":
      "Assurez-vous que le mot de passe correspond.",
  "Save": "Enregistrer",
  "Re-enter New Password": "Ressaisir le nouveau mot de passe",
  "Contact Us": "Contactez-nous",
  "app dec": "découverte de l'application",
  "About the application": "À propos de l'application",
  "Password must be at least 4 characters long":
      "Le mot de passe doit comporter au moins 4 caractères",
  "Select": "Sélectionner",
  "View All Missions": "Voir toutes les missions",
  "The password field is incorrect": "Le champ du mot de passe est incorrect",
  "is required.": "est requis.",
  "Username is required": "Le nom d'utilisateur est requis",
  "No Missions found": "Aucune mission trouvée",
  "The username field is invalid.":
      "Le champ du nom d'utilisateur est invalide.",
  "This user is blocked": "Cet utilisateur est bloqué.",
  "Photos": "Photos",
  "Password is required": "Le mot de passe est requis",
  "Username must be at least 4 characters long":
      "Le nom d'utilisateur doit comporter au moins 4 caractères",
  "Camera": "Appareil photo",
  "Actions": "Actions",
  "Mission created successfully!": "Mission créée avec succès !",
  "Status": "Statut",
  "Creator": "Créateur",
  "Label": "Étiquette",
  "Last Missions": "Dernières missions",
  "Select another annex": "Sélectionnez une autre annexe",
  "No company found, please select another annex.":
      "Aucune entreprise trouvée, veuillez sélectionner une autre annexe.",
  "View All Feedback": "Voir tous les Feedbacks",
  "Last Feedbacks": "Derniers Feedbacks",
  'New': 'Nouveau',
  'Unknown Status': 'Statut inconnu',
  'Confirmation': 'Confirmation',
  'Are you sure to Start the Mission?':
      'Êtes-vous sûr de commencer la mission ?',
  'Are you sure to Stop the Mission?':
      'Êtes-vous sûr de vouloir arrêter la mission ?',
  'No description available': 'Aucune description disponible',
  'Created At': 'Créé le',
  'Editor Username': 'Nom d\'utilisateur de l\'éditeur',
  'No editor assigned': 'Aucun éditeur assigné',
  'Creator Username': 'Nom d\'utilisateur du créateur',
  "Add Feedback": "Ajouter un Feedback",
  'Feedback Details': 'Détails du Feedback',
  'Are you sure to complete the Mission?':
      'Êtes-vous sûr de vouloir compléter la mission ?',
  'Other Details': 'Autres détails',
  'Region:': 'Région :',
  'Create Feedback': 'Créer un Feedback',
  'Sold:': 'Vendu :',
  'Turnover:': 'Chiffre d\'affaires :',
  'Cashing In:': 'Encaissement :',
  'This field': 'Ce champ',
  'must be at least': 'doit contenir au moins',
  'characters.': 'caractères.',
  "is required": "est requis",
  "must be no more than": "ne doit pas dépasser",
  "characters": "caractères",
  "Email is required": "L'email est requis",
  "Please enter a valid email address":
      "Veuillez entrer une adresse e-mail valide",
  "Password must be at least": "Le mot de passe doit contenir au moins",
  "Phone number is required": "Le numéro de téléphone est requis",
  "Please enter a valid phone number":
      "Veuillez entrer un numéro de téléphone valide",
  ' is required.': ' est requis.',
  'Potential:': 'Potentiel :',
  'Please enter a valid phone number.':
      'Veuillez entrer un numéro de téléphone valide.',
  "Client Since:": "Client depuis :",
  'Contact Details': 'Détails de contact',
  "Report": "Rapport",
  "Created by:": "Créé par :",
  "My Feedbacks": "Mes Feedbacks",
  'Client Profile': 'Profil du client',
  'No Date Available': 'Aucune date disponible',
  'Feedback not found.': 'Feedback non trouvé.',
  'No Name': 'Aucun nom',
  "Search clients...": "Rechercher des clients...",
  'No clients available.': 'Aucun client disponible.',
  "Select the client": "Sélectionnez le client",
  'No Email': 'Aucun email',
  "Client": "Client",
  'No Title': 'Aucun titre',
  "Email": "Email",
  "Add Mission": "Ajouter une mission",
  'Request Date:': 'Date de demande :',
  "Start Mission": "Démarrer la mission",
  "Missions": "Missions",
  'Select End Date': 'Sélectionner la date de fin',
  "Mission Details": "Détails de la mission",
  'Phone': 'Téléphone',
  'Address': 'Adresse',
  'Business Information': 'Informations sur l\'entreprise',
  'End Date:': 'Date de fin :',
  'Creator Information': 'Informations sur le créateur',
  'Username:': 'Nom d\'utilisateur :',
  'Open Settings': 'Ouvrir les paramètres',
  "Date:": "Date :",
  'Edit Feedback': 'Modifier le Feedback',
  'Gallery': 'Galerie',
  'Location services are required for this feature. Please enable them in settings.':
      'Les services de localisation sont requis pour cette fonctionnalité. Veuillez les activer dans les paramètres.',
  'Location Services Disabled': 'Services de localisation désactivés',
  'No Images available': 'Aucune image disponible',
  'Select Start Date': 'Sélectionner la date de début',
  'Start Date:': 'Date de début :',
  'Select Date Range': 'Sélectionner la plage de dates',
  'No missions available': 'Aucune mission disponible',
  'Language Selection': 'Sélection de la langue',
  'Choose your preferred language to make it easier for you to use the application':
      'Choisissez votre langue préférée pour faciliter l\'utilisation de l\'application',
  "My Missions": "Mes missions",
  'No companies available.': 'Aucune entreprise disponible.',
  'Description': 'Description',
  "Edit Profile": "Modifier le profil",
  'Selected Images': 'Images sélectionnées',
  'Loading images:': 'Chargement des images :',
  "Failed to load reasons:": "Échec du chargement des raisons :",
  'Update Feedback': 'Mettre à jour le Feedback',
  'No reasons available': 'Aucune raison disponible',
  'Please enter a description': 'Veuillez entrer une description',
  'Create Mission': 'Créer une mission',
  'Companies': 'Entreprises',
  'Updated:': 'Mis à jour :',
  "Description Required *": "Description requise *",
  'Created:': 'Créé :',
  "Request Date Required *": "Date de demande requise *",
  "Change Language": "Changer la langue",
  "This feedback has a mission.": "Ce Feedback d'information a une mission.",
  'Company name:': 'Nom de l’entreprise :',
  "A new version of the app is available. Update now to enjoy the latest features and improvements.":
      "Une nouvelle version de l'application est disponible. Mettez à jour maintenant pour profiter des dernières fonctionnalités et améliorations.",
  "Later": "Plus tard",
  "Update Now": "Mettre à jour maintenant",
  "Full Name": "Nom complet",
  "About the Application": "À propos de l'application",
  'We introduce an exclusive application designed for customer delegates, enabling them to effortlessly record their notes. This app facilitates the organization of information and the effective tracking of customer interactions, ultimately enhancing service quality and improving the overall customer experience.':
      'Nous vous présentons une application exclusive conçue pour les délégués clients, leur permettant d\'enregistrer facilement leurs notes. Cette application facilite l\'organisation des informations et le suivi efficace des interactions avec les clients, améliorant ainsi la qualité du service et l\'expérience globale du client.',
  "Tel": "Téléphone",
  'Start': 'Démarrer',
  'Owner Respond': 'Propriétaire Répond',
  'Responsible Respond': 'Répond Responsable',
  'Responsible close': 'Fermeture Responsable',
  'Close': 'Fermer',
  'Responsible:': 'Responsable:',
  'View All Task': 'Voir Toutes les Tâches',
  'No Task found': 'Aucune tâche trouvée',
  'Since': 'Depuis',
  'Responsible': 'Responsable',
  'Last Tasks': 'Dernières Tâches',
  'Revert cancellation': 'Annuler l\'annulation',
  'My Assigned': 'Mon Assigné',
  'My Created': 'Ma Créé',
  'My Supervised': 'Mon Supervisé',
  'message': 'message',
  'Type a message...': 'Tapez un message...',
  'File': 'Fichier',
  'Task not found': 'Tâche non trouvée',
  'Task Details': 'Détails de la tâche',
  'Create At': 'Créé à',
  'Deadline': 'Date limite',
  'Started': 'Démarré',
  'Not started': 'Pas commencé',
  'Observer': 'Observateur',
  'Owner': 'Propriétaire',
  'PDF Gallery': 'Galerie PDF',
  'All files': 'Tous les fichiers',
  'Image Gallery': 'Galerie d\'images',
  'Histories': 'Histoires',
  'Discussion': 'Discussion',
  'Information': 'Information',
  'Invalid Date': 'Date invalide',
  'Unknown': 'Inconnu',
  'No Task available': 'Aucune tâche disponible',
  'All Task': 'Toutes les tâches',
  'Update': 'Mettre à jour',
  'Label must be at least 4 characters long':
      'L\'étiquette doit comporter au moins 4 caractères',
  'Label is required': 'L\'étiquette est requise',
  'Select Observator': 'Sélectionner l\'observateur',
  'Select Responsable': 'Sélectionner le responsable',
  'Edite Task': 'Éditer la tâche',
  'add Task': 'Ajouter une tâche',
  'Description must be at least 4 characters long':
      'La description doit comporter au moins 4 caractères',
  'Description is required': 'La description est requise',
  'Create Task': 'Créer une tâche',
  'Pick a date': 'Choisir une date',
  'Selected Date': 'Date sélectionnée',
  'Files': 'Fichiers',
  'Expired': 'Expiré',
  'Remaining:': 'Restant:',
  'year': 'an',
  'day': 'jour',
  'hour': 'heure',
  'minute': 'minute',
  'second': 'seconde',
  'Add \n Task': 'Ajouter \n une tâche',
  'Statistics Tasks': 'Statistiques des tâches',
  'Responsible Closed': 'Fermé Responsable',
  'error fetching data': 'Erreur de récupération des données',
  'Task': 'Tâche',
  'Closed': 'Fermé',
  'ago': 'il y a',
  'Failed to update task status':
      'Échec de la mise à jour du statut de la tâche',
  'Error fetching Task data': 'Erreur de récupération des données de la tâche',
  'Task created successfully': 'Tâche créée avec succès',
  'Failed to create task': 'Échec de la création de la tâche',
  'Error updating task': 'Erreur de mise à jour de la tâche',
  'Task updated successfully': 'Tâche mise à jour avec succès',
};
