const Map<String, String> fr = {
  'Login Screen': 'Connectez-vous à votre compte',
  "Username": "Nom d'utilisateur",
  'Write Username': "Entrez le nom d'utilisateur",
  'Password': "Mot de passe",
  'Write Password': "Entrez le mot de passe",
  'Login': "Connexion",
  'Please fill in the blank fields.': "Veuillez remplir les champs vides.",
  'Failed to login. Invalid response.':
      "Échec de la connexion. Réponse invalide.",
  'Oops! It seems there was an issue with your request. Please try again.':
      "Oups! Il semble qu'il y ait un problème avec votre demande. Veuillez réessayer.",
  'Access Denied! You don\'t have permission to view this content.':
      "Accès refusé! Vous n'avez pas la permission de voir ce contenu.",
  'Sorry, we couldn\'t find what you were looking for. Please try again later.':
      "Désolé, nous n'avons pas pu trouver ce que vous cherchiez. Veuillez réessayer plus tard.",
  'Something went wrong. Please try again or contact support if the issue persists.':
      "Un problème est survenu. Veuillez réessayer ou contacter le support si le problème persiste.",
  'username is invalid': "Le nom d'utilisateur est invalide",
  'the password is wrong': "Le mot de passe est incorrect",
  'Please check your internet connection.':
      "Veuillez vérifier votre connexion Internet.",
  'No internet connection': "Pas de connexion Internet.",
  'Cancel': "Annuler",
  'Connection problem': "Problème de connexion",
  'Verifying...': "Vérification...",
  "Delegate": "Déléguer",
  "Every thing \nunder controlle": "Tout est \nsous contrôle",
  "Get Started": "Commencer",
  "You are not allowed to enter.": "Vous n'êtes pas autorisé à entrer.",
  "OK": "D'accord",
  "Please specify": "Veuillez préciser",
  "Select Reasons": "Sélectionnez les raisons",
  "Loading data...": "Chargement des données...",
  "Your account is blocked, please contact our support team.":
      "Votre compte est bloqué, veuillez contacter notre équipe de support.",
  "Select Date": "Sélectionner la date",
  "Profile": "Profil",
  "Feedbacks": "Commentaires",
  "My FeedBack": "Mon commentaire",
  "All Clients": "Tous les clients",
  "ALL Missions": "TOUTES les missions",
  "My Mission": "Ma mission",
  "No Company found": "Aucune entreprise trouvée",
  "Select Company": "Sélectionner l'entreprise",
  "No Annex found": "Aucun annexe trouvé",
  "Select Annex": "Sélectionner l'annexe",
  "Loading name...": "Chargement du nom...",
  "Add \n Mission": "Ajouter \n Mission",
  "Add \n Feedback": "Ajouter \n Commentaire",
  "Percentage": "Pourcentage",
  "With Mission": "Avec mission",
  "With Out Mission": "Sans mission",
  "All": "Tous",
  "Statistics Feedback": "Statistiques des commentaires",
  "Completed": "Terminé",
  "In Progress": "En cours",
  "Canceled": "Annulé",
  "Statistics Missions": "Statistiques des missions",
  "Log Out": "Déconnexion",
  'Do you really want to log out of the account?':
      'Voulez-vous vraiment vous déconnecter du compte ?',
  "Quick Actions": "Actions rapides",
  "Settings and Preferences": "Paramètres et préférences",
  'Selected language': 'Langue sélectionnée',
  'Fetching data...': 'Récupération des données...',
  "Active": "Actif",
  "Inactive": "Inactif",
  "In English is \"Verifying...\"": "En anglais, c'est \"Vérification...\"",
  "Account": "Compte",
  "Annex": "Annexe",
  "Company": "Entreprise",
  "Version.": "Version.",
  "Send Your Suggestion": "Envoyez votre suggestion",
  "Write your opinion or suggestion here...":
      "Écrivez votre opinion ou votre suggestion ici...",
  "Suggestions": "Suggestions",
  "User Information": "Informations utilisateur",
  "Edit Information": "Modifier les informations",
  "First Name": "Prénom",
  'Please enter a First Name': 'Veuillez entrer un prénom',
  "Last Name": "Nom de famille",
  'Please enter a last Name': 'Veuillez entrer un nom de famille',
  "Edit Basic Information": "Modifier les informations de base",
  "Change Password": "Changer le mot de passe",
  "Current Password": "Mot de passe actuel",
  "Enter Current Password": "Entrez le mot de passe actuel",
  'Please enter a Current Password': 'Veuillez entrer un mot de passe actuel',
  "New Password": "Nouveau mot de passe",
  "Enter New Password": "Entrez le nouveau mot de passe",
  'Please enter a New Password': 'Veuillez entrer un nouveau mot de passe',
  "Confirm Password": "Confirmer le mot de passe",
  "Enter the New Password": "Entrez le nouveau mot de passe",
  'Please enter a Confirm Password':
      'Veuillez entrer une confirmation de mot de passe',
  "Make sure the password matches.":
      "Assurez-vous que le mot de passe correspond.",
  "Save": "Enregistrer",
  "Contact Us": "Contactez-nous",
  "app dec": "découverte de l'application",
  "About the application": "À propos de l'application",
  "View All Missions": "Voir toutes les missions",
  "No Missions found": "Aucune mission trouvée",
  "Status": "Statut",
  "Creator": "Créateur",
  "Label": "Étiquette",
  "Last Missions": "Dernières missions",
  "Select another annex": "Sélectionnez une autre annexe",
  "No company found, please select another annex.":
      "Aucune entreprise trouvée, veuillez sélectionner une autre annexe.",
  "View All Feedback": "Voir tous les commentaires",
  "Last Feedbacks": "Derniers commentaires",
  'New': 'Nouveau',
  'Unknown Status': 'Statut inconnu',
  'Confirmation': 'Confirmation',
  'Are you sure to Start the Mission?':
      'Êtes-vous sûr de commencer la mission ?',
  'Are you sure to Stop the Mission?':
      'Êtes-vous sûr de vouloir arrêter la mission ?',
  'No description available': 'Aucune description disponible',
  'Created At': 'Créé le',
  'Editor Username': 'Nom d\'utilisateur de l\'éditeur',
  'No editor assigned': 'Aucun éditeur assigné',
  'Creator Username': 'Nom d\'utilisateur du créateur',
  "Add Feedback": "Ajouter un commentaire",
  "Start Mission": "Démarrer la mission",
  'Select End Date': 'Sélectionner la date de fin',
  'End Date:': 'Date de fin :',
  'Select Start Date': 'Sélectionner la date de début',
  'Start Date:': 'Date de début :',
  'Select Date Range': 'Sélectionner la plage de dates',
  'No missions available': 'Aucune mission disponible'
};
